keep-starknet-strange/awesome-starknet

README.md

Jupyter notebook support for Cairo. If it would make more sense to create a new subcategory for `Jupyter` within Editor Plugins, happy to move it there.

add cario_kernel

---

README.md

Starknet.py was recently released to pypi, with functionality and purpose similar to starknet.js

Add starknet.py library

---

README.md

added chainsecurity's audit of maker's dai bridge to the security section

feat: makerdao dai bridge audit

---

README.md

I created a StarkNet library in Rust. It's meant to achieve at least functional parity with `starknet.js` and `starknet.py`.
The version currently [published](https://crates.io/crates/starknet) to crates.io offers full sequencer API coverage.

Add starknet-rs library

---

README.md

I've added the [briq](https://briq.construction/) repo in the list of projects `Built / Deployed on StarkNet`.

Add briq in the list of projects built / deployed on StarkNet

---

README.md

Adds the following VS code extension for code assistance and compile error highlighting:  https://marketplace.visualstudio.com/items?itemName=ericglau.cairo-ls
(This can be used along with StarkWare's Cairo VS Code)

Add VS Code extension for code assistance

---

README.md

Add [starknet-cairo-101](https://github.com/l-henri/starknet-cairo-101) to the Examples section

Add starknet-cairo-101 to Examples

---

README.md

I added the React hooks library for StarkNet that I released the other day.

Add starknet-react library

---

README.md

Add Full-Stack StarkNet to Tutorials section: https://github.com/sambarnes/fullstack-starknet
Contribution guidelines recommended alphabetical order, but it wasn't sorted that way already.
Lmk and I can either alphabetize the whole thing or just throw mine at the end of the section 👍 

Add Full-Stack StarkNet to Tutorials section

---

README.md

[Protostar](https://docs.swmansion.com/protostar/) allows user to:
- manage dependencies,
- compiling contracts,
- testing Cairo code in Cairo (including cheatcodes).
More features are planned (like dramatic test speed improvements). Protostar doesn't require python to run.

Add protostar

---

README.md

Add Starklings interactive cairo development tutorials: https://github.com/onlydustxyz/starklings.

Add Starklings Tutorials

---

README.md

The linked resource does not anymore exist.

Remove dead repo

---

README.md

Added starknet-jvm, library for jvm languages.

Add starknet-jvm

---

README.md

Added the oracle [Empiric Network](https://empiric.network/) to the "built / deployed" section. Added it to the bottom since there is currently no alphabetic ordering. I can update this PR or make a new one where all entries are sorted if that's preferred.

Add Empiric Network to "Built / Deployed" section

---

README.md

Added ape-starknet and ape-cairo plugins 

add ape-starknet ape-cairo

---

README.md

Adding starknet-edu content
- [ X] The URL is not already present in the list (check with CTRL/CMD+F in the
- [X ] Each description starts with an uppercase character and ends with a
- [X ] Drop all `A` / `An` prefixes at the start of the description.
- [ X] Avoid using the word `StarkNet` in the description.

Added StarkNet edu tutorials and content

---

README.md

Add [Starknet by Example](https://starknet-by-example.voyager.online/).

Add Starknet by Example

---

README.md

update gh org for caigo SN golang repo

chore: updated caigo home

---

CAIRO_0_ARCHIVE.md
PULL_REQUEST_TEMPLATE.md
README.md

Move the current `README.md` in `CAIRO_0_ARCHIVE.md` and created a new one based on the current Starknet Ecosystem (with Cairo 1).

feat: Cairo 1 update

---

README.md

Add cairo plugins.
Removes deadlinks, duplicates to fix CI.
Close #57 as well

Feat: cairo plugins

---

README.md

I added the Kraken Sequencer to the Sequencer list

Adds Kraken Sequencer

---

README.md

Abigen is [deprecated](https://github.com/glihm/starknet-abigen-rs?tab=readme-ov-file#%EF%B8%8F-archived-%EF%B8%8F) in favor of Cainome

cainome link

---

README.md

Added types-js and starknet-devnet-js

---

README.md

Ethereum Ecosystem is the Unofficial Ecosystem page for Ethereum and some of its Layer 2s (including Starknet).
Link: https://www.ethereum-ecosystem.com/blockchains/starknet

Adding Ethereum Ecosystem

---

README.md

Fixes #91
This PR updates the link for Cairo Documentation to resolve the 404 error.
Changes made:
- Updated the Cairo Documentation link from https://www.cairo-lang.org/docs/index.html to https://docs.cairo-lang.org/
This change ensures users are directed to the correct, up-to-date Cairo documentation.

Update Cairo Documentation link to resolve 404 error

---

README.md

Fixes #93 
This PR adds the link to the live interactive web-based version of Starklings alongside the existing GitHub repository link.
Changes made:
- Updated the Starklings entry to include both the GitHub repository and the live interactive version links.
This enhancement provides users with both options: exploring the source code and running Starklings locally via the GitHub repository, as well as trying it out immediately through the web-based version.

Add live interactive Starklings link alongside GitHub repository

---

README.md

Fixes #95 
This PR removes the WTF Starknet resource from the README due to multiple issues with outdated content and lack of maintenance.
Changes made:
- Removed the entry for WTF Starknet from the list of resources.
This change ensures that our list continues to provide only up-to-date and actively maintained resources, maintaining the quality and relevance of the Awesome Starknet list.

Remove outdated WTF Starknet resource

---

README.md

Fixes #97 
This PR adds the Exercism Cairo track to the Tutorials and Examples section.
Changes made:
- Added an entry for the Exercism Cairo track in the Tutorials and Examples section.
This addition provides users with a structured, interactive approach to learning Cairo through hands-on exercises and community mentorship, enhancing the variety of learning resources in our list.

Add Exercism Cairo track to Tutorials and Examples

---

README.md

Custom Vim setup links for Cairo1 syntax highlighting and coc.nvim language server.

Add Vim syntax highlighting and CoC LS links

---

README.md

Fixes #105
Changing broken links to current ones:
Katana - High performance sequencer that can be used as a local testnet. -> new link is https://book.dojoengine.org/toolchain/katana
starknet.dart(https://starknetdart.dev/) - Dart library for mobile. -> New link: https://github.com/focustree/starknet.dart

Update broken links to current ones

---

README.md

Fixes #120
Added Chainlink Data Feed (https://docs.chain.link/data-feeds/price-feeds/addresses?network=starknet&page=1&search=) and Pyth Data Feed (https://www.pyth.network/price-feeds) to Oracles section

Add Pyth and Chainlink Data Feeds

---

README.md

Changes made: Adding Build a Game with Dojo workshop
Reason to add it: 
This tutorial teaches how to build a game using Dojo, a Provable Game Engine on Starknet. It’s valuable for developers interested in exploring the gaming and blockchain intersection, using Starknet’s infrastructure to create games with verifiable logic.

Add Dojo workshop

---

README.md

Partially fixes #126 
Changes made: Add Starknet CC recordings
Reason to add it: This playlist contains talks from Starknet CC 2024, providing access to a high quality information from various experts in the Starknet ecosystem. These talks are essential for staying up-to-date on the latest developments, use cases, and best practices in Starknet.
This should be updated after each StarknetCC

Add StarknetCC 2024 recordings

---

README.md

Changes made: Adding Analyzing onchain data with Apibara Integrations workshop 
Reason to add this: This resource offers a practical guide on how to analyze on-chain data on Starknet using Apibara, integrating with ChatGPT. It provides valuable insights for developers and data analysts looking to leverage Starknet's data for various use cases.

Adding Apiraba workshop

---

README.md

Fixes #137
Changes made: update Starknet.id link to the current one (https://github.com/lfglabs-dev)

Starknet.id link updated

---

README.md

Fixes #101
Changes made:
- Adding new section for Video Resources, including Basecamp X

Adding video resources section
