keep-starknet-strange/awesome-starknet

- README.md
Added a list of jobs curated from the community jobs channel on StarkNet discord
- [X ] The URL is not already present in the list (check with CTRL/CMD+F in the
- [X ] Drop all `A` / `An` prefixes at the start of the description.
> Added jobs

- README.md
> Adding StarkWare YT channel

- README.md
addition of Caigo: golang library and Vue.js boilerplate projects
> caigo: golang library && Vue.js boilerplate

- README.md
Add the notion site that [@natimuril] (https://twitter.com/natimuril) put together containing resources
> added notion site

- README.md
> Add StarkTx Transaction Decoder

- README.md
Added Fossil L1 State verification tool
> Add Fossil tool

- README.md
Adds [Contracts Wizard for Cairo](https://wizard.openzeppelin.com/cairo) to the Templates category.
Contracts Wizard for Cairo is an interface to interactively build a smart contract out of components from OpenZeppelin Contracts for Cairo. Select the kind of contract that you want, set your parameters and desired features, and the Wizard will generate all of the code necessary. The resulting code is ready to be compiled and deployed, or it can serve as a starting point and customized further with application specific logic.
> Add Contracts Wizard for Cairo

- README.md
- [ v] The URL is not already present in the list (check with CTRL/CMD+F in the
- [ v] Each description starts with an uppercase character and ends with a
- [ v] Drop all `A` / `An` prefixes at the start of the description.
- [ v] Avoid using the word `StarkNet` in the description.
> added missing wallet & the starkware's baked get-starknet library

- README.md
Add Amarna static analyzer and Tayt StarkNet smart contract fuzzer by Trail of Bits
> Add Amarna and Tayt

- PULL_REQUEST_TEMPLATE.md
- README.md
> Adding a new section: Cryptography; added first paper in the Cryptography section

- README.md
> Add link to Equilibrium Labs careers page under "Jobs"

- README.md
> Add nori to open-source infrastructure

- README.md
- [V] The URL is not already present in the list (check with CTRL/CMD+F in the
- [V] Each description starts with an uppercase character and ends with a
- [V] Drop all `A` / `An` prefixes at the start of the description.
- [V] Avoid using the word `Starknet` in the description.
> Add batchor ERC20 CSV

- README.md
Add Ethereum Ecosystem to awesome-starknet. It's featured on starknet's website here: https://www.starknet.io/en/ecosystem/dapps
> Add Ethereum Ecosystem

- README.md
> Cairo zero to hero basecamp link

- README.md
Add a link to Starknet MEV community group in Telegram
> MEV community group link

- README.md
Fixes #100 
Adding Foundation YT channel, it has a good amount of technical videos and they share workshops recordings.
> Foundation YT channel

- README.md
> Add `cairo-profiler`

- README.md
Adding reference to `scarbs.xyz` package registry.
> Update README.md - Adding reference to scarbs.xyz

- README.md
Fixes #108
Adding Cairo Playground https://www.cairo-lang.org/cairovm/ to Official Resources
> Adding Cairo Playground

- README.md
Fixes #114
Adding https://www.starknet.io/wallets/ as a resource to find all the wallets available on Starknet
> List of wallets added

- README.md
Fixes #118
Adding Scaffold Stark and Starknet Scaffold resources
> Add dapps libraries

- README.md
Partially fixes #126 
Change made: Adding Account Abstraction wokshop repo
Reason to add it: This workshop helps developers practice creating an account contract with a single signer that uses the STARK-friendly elliptic curve to sign transactions. It's very helpful to understand how AA works on Starknet and to challenge devs to complete each step.
> Add Account Abstraction workshop

- README.md
Changes made: Adding STARK 101
Reason to add it:  It’s a foundational resource for anyone wanting to deeply understand the cryptographic technology behind Starknet.
> Add STARK 101

- README.md
Changes made: Adding Counter workshop
Reason to add it: This repository offers a hands-on, step-by-step guide to writing smart contracts with Cairo. It’s an ideal starting point for developers new to Cairo and Starknet who want to build basic smart contract functionality, also it's used in Basecamp.
> Add counter workshop

- README.md
Changes made: Adding Starknet AI agent
Reason to add it: This tool offers a way to expand their Starknet technical knowlegde using an AI agent, using Cairo Book and Starknet docs to provide answers.
> Add Starknet AI agent

- README.md
> feat: add Fibrous public repos

- README.md
> Vesu liquidator bot and contract
